### ISSUE TITLE
Specs fail on bundled gem on rubyci.org

### ISSUE THREAD

**Issue by mjago** [ruby/chkbuild#29]
I wrote some specs for DidYouMean module to satisfy [ruby/spec issue #175](https://github.com/ruby/spec/issues/175).
These specs pass on ruby/spec CI (travis and appveyor).

However these specs fail all platforms on rubyci.org due to the specs being run before bundled gems (including did_you_mean) are downloaded - and were therefore [reverted (PR #352)](https://github.com/ruby/spec/pull/352).

Is this sequence by design on [rubyci.org](http://rubyci.org/) or should running specs be deferred until bundled gems are downloaded?

**Comment by eregon** [comment]
Ping @akr @hsbt.

It also seems that `did_you_mean` is currently not tested at all?
Maybe `did_you_mean` own tests should run on the built ruby?

**Comment by hsbt** [comment]
For my personal opinion, We should not test bundled_gems such as did_you_mean, rake and etc.

To maintain these gems leave from ruby core (and ruby/spec) responsibility.

**Comment by eregon** [comment]
My concern is some change in MRI could break the bundled version of `did_you_mean`.
Without automatic testing, we will only know when a user reports it, which is fairly late (usually after release).

For me, the only difference between bundled gems and stdlib is the packaging, both should be tested on MRI since they both come "with it". Otherwise there is a high risk to ship broken parts in a release.

**Comment by hsbt** [comment]
> My concern is some change in MRI could break the bundled version of did_you_mean.

Agreed. I didn't provide this guard solution yet...

**Comment by hsbt** [comment]
There is no plan to merge `test-bundled-gems` into chkbuild.
